DROP TABLE IF EXISTS users;

CREATE TABLE users (id BIGINT AUTO_INCREMENT PRIMARY KEY,
user_name VARCHAR(20) NOT NULL, email_address VARCHAR(250) NOT NULL,
password VARCHAR(120), last_login TIMESTAMP);